//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinephile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Id = Guid.NewGuid();
            this.MoviesPlayedIn = new HashSet<Movie>();
            this.MoviesDirected = new HashSet<Movie>();
        }
    
        public System.Guid Id { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int CounryId { get; set; }
        public string PicturePath { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Movie> MoviesPlayedIn { get; set; }
        public virtual ICollection<Movie> MoviesDirected { get; set; }
    }
}
