//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinephile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Id = Guid.NewGuid();
            this.Ratings = new HashSet<Rating>();
            this.Reviews = new HashSet<Review>();
            this.Actors = new HashSet<Artist>();
            this.Countries = new HashSet<Country>();
            this.Directors = new HashSet<Artist>();
            this.Genres = new HashSet<Genre>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Storyline { get; set; }
        public System.DateTime ReleseDate { get; set; }
        public int RunningTime { get; set; }
        public int LanguageId { get; set; }
        public string PosterPath { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Artist> Actors { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<Artist> Directors { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
